# SPDX-License-Identifier: Apache-2.0.
# Copyright (C) 2026-present ahrs-monitor project and contributors.

# AHRS Monitor configurations.

# IMU configurations.
[imu]
# IMU sample rate in Hz.
sample_rate = 200.0
# IDTP payload type.
payload_type = 0x03 # 0x03 - Imu6 (for MPU-6050).
# IMU device identifier.
device_id = 0x66
# Protocol operating mode.
protocol_mode = 0x01

# Networks configurations.
[net]
# Monitor's IP address.
monitor_ip = "192.168.6.2"
# Monitor's UDP port.
monitor_port = 12345
# IMU's gateway IP address.
imu_gateway_ip = "192.168.6.1"
# IMU's gateway SSID.
imu_gateway_ssid = "AHRS_Direct"
# IMU's gateway password.
imu_gateway_password = "1234567890"
# Simulator's IP address.
simulator_ip = "127.0.0.1"
# Simulator's UDP port.
simulator_port = 1234
# Flag whether to use encryption for IMU data transmission.
use_encryption = true

# Logging configurations.
[log]
# Directory where logs are stored.
directory = "..\\logs"
